# Generated by Django 3.1.7 on 2021-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db_todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaPekerjaan', models.CharField(max_length=200)),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'ongoing'), ('1', 'done')], default=0, max_length=200)),
            ],
        ),
    ]
